### ISSUE TITLE
Report Broken

### ISSUE THREAD

**Issue by saikrishna321** [jaydeepc/report_pytest#37]
<img width="1394" alt="screen shot 2017-10-01 at 11 55 19 pm" src="https://user-images.githubusercontent.com/4045041/31057647-d6021d94-a703-11e7-9971-c4313baf97e9.png">

Given Data:
```
{
  "report": {
    "summary": {
      "Passed": 2,
      "Suite Name": "TestNG Test0",
      "Failed": 1,
      "Skipped": 0,
      "Included Groups": "[Ljava.lang.String;@30c15d8b",
      "Invoked Methods": 3,
      "Duration": "90 seconds"
    },
    "tests": [
      {
        "testDetails": {
          "classname": "LoginTest",
          "endtime": 1506874146,
          "starttime": 1506874108,
          "results": "Fail",
          "logs": {
            "adbLogs": "adblogs/0715f742cdb53836__loginTest.txt",
            "screenShotFailure": "screenshot/android/0715f742cdb53836/LoginTest/loginTest/2017-10-01T21:39:09SM-G920I_samsung_loginTest_failed.jpeg"
          },
          "exceptiontrace": "org.openqa.selenium.WebDriverException: unknown error: Element is not clickable at point (55, 7330)\n (Session info: chrome=61.0.3163.98)\n (Driver info: chromedriver=2.30.477690 (c53f4ad87510ee97b5c3425a14c0e79780cdf262),platform=Mac OS X 10.12.6 x86_64) (WARNING: The server did not provide any stacktrace information)\nCommand duration or timeout: 0 milliseconds\nBuild info: version: '3.5.3', revision: 'a88d25fe6b', time: '2017-08-29T12:42:44.417Z'\nSystem info: host: 'INshridhk.local', ip: 'fe80:0:0:0:1083:3cda:692c:aa0f%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_65'\nDriver info: io.appium.java_client.android.AndroidDriver\nCapabilities [{deviceScreenSize=1440x2560, networkConnectionEnabled=true, warnings={}, databaseEnabled=false, deviceName=0715f742cdb53836, platform=LINUX, deviceUDID=0715f742cdb53836, desired={platformVersion=7.0, browserName=chrome, takesScreenshot=true, chromeDriverPort=49356, platformName=Android, udid=0715f742cdb53836, deviceName=android}, platformVersion=7.0, webStorageEnabled=false, locationContextEnabled=false, takesScreenshot=true, browserName=chrome, javascriptEnabled=true, chromeDriverPort=49356, deviceModel=SM-G920I, udid=0715f742cdb53836, deviceManufacturer=samsung, platformName=LINUX}]\nSession ID: 3e3ded46-167a-4d7b-baec-5238a6370704",
          "methodname": "loginTest"
        },
        "totaltime": 1505367272,
        "model": "SM-G920I_samsung",
        "id": "0715f742cdb53836",
        "version": "7.0",
        "platform": "ANDROID"
      },
      {
        "testDetails": {
          "classname": "LoginTest",
          "endtime": 1506874171,
          "starttime": 1506874152,
          "results": "Pass",
          "logs": {
            "adbLogs": "adblogs/0715f742cdb53836__loginTest1.txt"
          },
          "exceptiontrace": "null",
          "methodname": "loginTest1"
        },
        "totaltime": 1505367297,
        "model": "SM-G920I_samsung",
        "id": "0715f742cdb53836",
        "version": "7.0",
        "platform": "ANDROID"
      },
      {
        "testDetails": {
          "classname": "LoginTest",
          "endtime": 1506874193,
          "starttime": 1506874174,
          "results": "Pass",
          "logs": {
            "adbLogs": "adblogs/0715f742cdb53836__loginTest3.txt"
          },
          "exceptiontrace": "null",
          "methodname": "loginTest3"
        },
        "totaltime": 1505367319,
        "model": "SM-G920I_samsung",
        "id": "0715f742cdb53836",
        "version": "7.0",
        "platform": "ANDROID"
      }
    ]
  }
}
```

**Comment by jaydeepc** [comment]
Dude json format is wrong.. Can you make them lower case? For example,
"Pass" should be "pass"

**Comment by jaydeepc** [comment]
Also did you try from the branch "appium-test-distribution" ?

**Comment by jaydeepc** [comment]
Below is the format, which kind of json convention as well.

    {"report": {
    "summary": {
    "num_tests": 14,
    "passed": 7,
    "failed": 5,
    "error": 1,
    "skipped": 1,
    "duration": 150
    },
    "tests": [
        {
            "testDetails": {
                "classname": "HomePageTest2",
                "endtime": 1501679741,
                "starttime": 1501679720,
                "results": "Fail",
                "logs": {
                    "adbLogs": "adblogs/192.168.58.102:5555__testMethodOne1.txt",
                    "screenShotFailure": "../screenshots/test_the_values_returned_by_sell_through_api_are_correct.png"
                },
                "exceptiontrace": "org.openqa.selenium.NoSuchElementException: An element could not be located on the page using the given search parameters. (WARNING: The server did not provide any stacktrace information)\nCommand duration or timeout: 32 milliseconds\nFor documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html\nBuild info: version: '3.3.1', revision: '5234b325d5', time: '2017-03-10 09:10:29 +0000'\nSystem info: host: 'insaikrisv-2.local', ip: 'fe80:0:0:0:18aa:d59a:5229:ead0%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.5', java.version: '1.8.0_111'\nDriver info: io.appium.java_client.android.AndroidDriver\nCapabilities [{app=/Users/saikrisv/Documents/workspace/workspace1/TestNGParallelThreadBeforeClass/build/AndroidCalculator.apk, noSign=true, automationName=UIAutomator2, platformName=Android, udid=192.168.58.102:5555, deviceName=android, platform=ANY, systemPort=52460}]\nSession ID: 30c2cf7e-a779-4aae-add9-f14a39abbd72\n*** Element info: {Using=accessibility id, value=login}",
                "methodname": "testMethodOne1"
            },
            "totaltime": 2.6,
            "model": "iPhone 7",
            "id": "192.168.58.102:5555",
            "version": "6.0",
            "platform": "iOS"
        },
        {
            "testDetails": {
                "classname": "HomePageTest3",
                "endtime": 1501679747,
                "starttime": 1501679720,
                "results": "Error",
                "logs": {
                    "adbLogs": "adblogs/192.168.58.103:5555__testMethodOne3.txt"
                },
                "exceptiontrace": "null",
                "methodname": "testMethodOne3"
            },
            "totaltime": 3,
            "model": "GoogleNexus6_Android",
            "id": "192.168.58.103:5555",
            "version": "6.0",
            "platform": "ANDROID"
        },
        {
            "testDetails": {
                "classname": "HomePageTest2",
                "endtime": 1501679765,
                "starttime": 1501679744,
                "results": "Fail",
                "logs": {
                    "adbLogs": "adblogs/192.168.58.102:5555__testMethodOne2.txt",
                    "screenShotFailure": "../screenshots/test_user_can_not_retrieve_event_details_with_nonexisting_factid.png"
                },
                "exceptiontrace": "org.openqa.selenium.NoSuchElementException: An element could not be located on the page using the given search parameters. (WARNING: The server did not provide any stacktrace information)\nCommand duration or timeout: 363 milliseconds\nFor documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html\nBuild info: version: '3.3.1', revision: '5234b325d5', time: '2017-03-10 09:10:29 +0000'\nSystem info: host: 'insaikrisv-2.local', ip: 'fe80:0:0:0:18aa:d59a:5229:ead0%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.5', java.version: '1.8.0_111'\nDriver info: io.appium.java_client.android.AndroidDriver\nCapabilities [{app=/Users/saikrisv/Documents/workspace/workspace1/TestNGParallelThreadBeforeClass/build/AndroidCalculator.apk, noSign=true, automationName=UIAutomator2, platformName=Android, udid=192.168.58.102:5555, deviceName=android, platform=ANY, systemPort=52947}]\nSession ID: 0fc5be48-cf51-48f7-a365-7a443eb5770e\n*** Element info: {Using=accessibility id, value=login}",
                "methodname": "testMethodOne2"
            },
            "totaltime": 4,
            "model": "GooglePixelC_Android",
            "id": "192.168.58.102:5555",
            "version": "6.0",
            "platform": "ANDROID"
        },
        {
            "testDetails": {
                "classname": "HomePageTest3",
                "endtime": 1501679773,
                "starttime": 1501679748,
                "results": "Skip",
                "logs": {
                    "adbLogs": "adblogs/192.168.58.103:5555__testMethodOne4.txt"
                },
                "exceptiontrace": "null",
                "methodname": "testMethodOne4"
            },
            "totaltime": 4,
            "model": "GoogleNexus6_Android",
            "id": "192.168.58.103:5555",
            "version": "6.0",
            "platform": "ANDROID"
        },
        {
            "testDetails": {
                "classname": "HomePageTest1",
                "endtime": 1501679792,
                "starttime": 1501679772,
                "results": "Pass",
                "logs": {
                    "adbLogs": "adblogs/192.168.58.102:5555__testMethodOne1.txt"
                },
                "exceptiontrace": "null",
                "methodname": "testMethodOne1"
            },
            "totaltime": 8,
            "model": "GooglePixelC_Android",
            "id": "192.168.58.102:5555",
            "version": "6.0",
            "platform": "ANDROID"
        },
        {
            "testDetails": {
                "classname": "HomePageTest5",
                "endtime": 1501679799,
                "starttime": 1501679776,
                "results": "Pass",
                "logs": {
                    "adbLogs": "adblogs/192.168.58.103:5555__testMethodFive5.txt"
                },
                "exceptiontrace": "null",
                "methodname": "testMethodFive5"
            },
            "totaltime": 21,
            "model": "GoogleNexus6_Android",
            "id": "192.168.58.103:5555",
            "version": "6.0",
            "platform": "ANDROID"
        },
        {
            "testDetails": {
                "classname": "HomePageTest1",
                "endtime": 1501679811,
                "starttime": 1501679793,
                "results": "Pass",
                "logs": {
                    "adbLogs": "adblogs/192.168.58.102:5555__testMethodOne10.txt"
                },
                "exceptiontrace": "null",
                "methodname": "testMethodOne10"
            },
            "totaltime": 43,
            "model": "GooglePixelC_Android",
            "id": "192.168.58.102:5555",
            "version": "6.0",
            "platform": "ANDROID"
        },
        {
            "testDetails": {
                "classname": "HomePageTest4",
                "endtime": 1501679825,
                "starttime": 1501679802,
                "results": "Pass",
                "logs": {
                    "adbLogs": "adblogs/192.168.58.103:5555__testMethodFour.txt"
                },
                "exceptiontrace": "null",
                "methodname": "testMethodFour"
            },
            "totaltime": 5,
            "model": "GoogleNexus6_Android",
            "id": "192.168.58.103:5555",
            "version": "6.0",
            "platform": "ANDROID"
        },
        {
            "testDetails": {
                "classname": "HomePageTest1",
                "endtime": 1501679834,
                "starttime": 1501679812,
                "results": "Pass",
                "logs": {
                    "adbLogs": "adblogs/192.168.58.102:5555__testMethodOne11.txt"
                },
                "exceptiontrace": "null",
                "methodname": "testMethodOne11"
            },
            "totaltime": 5.3,
            "model": "GooglePixelC_Android",
            "id": "192.168.58.102:5555",
            "version": "6.0",
            "platform": "ANDROID"
        },
        {
            "testDetails": {
                "classname": "HomePageTest1",
                "endtime": 1501679859,
                "starttime": 1501679835,
                "results": "Pass",
                "logs": {
                    "adbLogs": "adblogs/192.168.58.102:5555__testMethodOne6.txt"
                },
                "exceptiontrace": "null",
                "methodname": "testMethodOne6"
            },
            "totaltime": 12,
            "model": "GooglePixelC_Android",
            "id": "192.168.58.102:5555",
            "version": "6.0",
            "platform": "ANDROID"
        },
        {
            "testDetails": {
                "classname": "HomePageTest1",
                "endtime": 1501679881,
                "starttime": 1501679860,
                "results": "Fail",
                "logs": {
                    "adbLogs": "adblogs/192.168.58.102:5555__testMethodOne7.txt",
                    "screenShotFailure": "../screenshots/test_user_can_not_retrieve_force_details_with_nonexisting_event_key.png"
                },
                "exceptiontrace": "org.openqa.selenium.NoSuchElementException: An element could not be located on the page using the given search parameters. (WARNING: The server did not provide any stacktrace information)\nCommand duration or timeout: 545 milliseconds\nFor documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html\nBuild info: version: '3.3.1', revision: '5234b325d5', time: '2017-03-10 09:10:29 +0000'\nSystem info: host: 'insaikrisv-2.local', ip: 'fe80:0:0:0:18aa:d59a:5229:ead0%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.5', java.version: '1.8.0_111'\nDriver info: io.appium.java_client.android.AndroidDriver\nCapabilities [{app=/Users/saikrisv/Documents/workspace/workspace1/TestNGParallelThreadBeforeClass/build/AndroidCalculator.apk, noSign=true, automationName=UIAutomator2, platformName=Android, udid=192.168.58.102:5555, deviceName=android, platform=ANY, systemPort=55168}]\nSession ID: 56dcefed-b989-4262-a05b-e1c1760840ff\n*** Element info: {Using=id, value=com.android2.calculator3:id/digit33}",
                "methodname": "testMethodOne7"
            },
            "totaltime": 23,
            "model": "GooglePixelC_Android",
            "id": "192.168.58.102:5555",
            "version": "6.0",
            "platform": "ANDROID"
        },
        {
            "testDetails": {
                "classname": "HomePageTest1",
                "endtime": 1501679902,
                "starttime": 1501679883,
                "results": "Pass",
                "logs": {
                    "adbLogs": "adblogs/192.168.58.102:5555__testMethodOne8.txt"
                },
                "exceptiontrace": "null",
                "methodname": "testMethodOne8"
            },
            "totaltime": 13,
            "model": "GooglePixelC_Android",
            "id": "192.168.58.102:5555",
            "version": "6.0",
            "platform": "ANDROID"
        },
        {
            "testDetails": {
                "classname": "HomePageTest1",
                "endtime": 1501679924,
                "starttime": 1501679903,
                "results": "Pass",
                "logs": {
                    "adbLogs": "adblogs/192.168.58.102:5555__testMethodOne9.txt"
                },
                "exceptiontrace": "null",
                "methodname": "testMethodOne9"
            },
            "totaltime": 7,
            "model": "GooglePixelC_Android",
            "id": "192.168.58.102:5555",
            "version": "6.0",
            "platform": "ANDROID"
        }
    ]
    }
    }
